"""first

Revision ID: 86e9e2462ce1
Revises: 
Create Date: 2022-09-08 15:38:01.289331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e9e2462ce1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_created'), 'endpoint', ['created'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_created'), 'role', ['created'], unique=False)
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('document', sa.String(length=14), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrator_created'), 'administrator', ['created'], unique=False)
    op.create_index(op.f('ix_administrator_email'), 'administrator', ['email'], unique=True)
    op.create_table('endpoint_role',
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('endpoint_id', 'role_id')
    )
    op.create_index(op.f('ix_endpoint_role_created'), 'endpoint_role', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_role_created'), table_name='endpoint_role')
    op.drop_table('endpoint_role')
    op.drop_index(op.f('ix_administrator_email'), table_name='administrator')
    op.drop_index(op.f('ix_administrator_created'), table_name='administrator')
    op.drop_table('administrator')
    op.drop_index(op.f('ix_role_created'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_endpoint_created'), table_name='endpoint')
    op.drop_table('endpoint')
    # ### end Alembic commands ###